### ISSUE TITLE
HueBot - Media Platform Configuration

### ISSUE THREAD

**Issue by alexisconia** [microsoftgraph/microsoft-graph-comms-samples#36] opened 2019-01-15 16:10 UTC
Hi,
I'm trying to start HueBot Sample on my dev host with ngrok. I configured all the settings but when i start a call, i got the message "Sorry, we couldn't connect you" in Teams. A message is also available in the logs "Notification queue app/calls/2e1a0f00-3370-45e2-bc20-2a73ba570aed is stopped".

After some investigations if i change the servicefqdn attribute (with the notification url) on media platform configuration, it's working. 

By default, my configuration is:
Notification URL : botdev.domain.com
Media URL for TCP : 1.bot.domain.com (CNAME of 1.tcp.eu.ngrok.io)
so servicefqdn=1.bot.domain.com

The configuration that is working:
Notification URL : botdev.domain.com
Media URL for TCP : 1.bot.domain.com (CNAME of 1.tcp.eu.ngrok.io)
servicefqdn=botdev.domain.com

According to this documentation https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots, the "standard" configuration is the first one.
Can you help me?
Thanks

**Comment by ksikorsk** [comment] 2019-03-14 16:50
Hello,

Thanks for reaching out.  It is surprising that the configuration that is working for you is the botdev.domain.com.  Are you deploying this bot to azure, or trying to run it locally?  The article you referenced is for local (on your dev box) development, and is not meant to be deployed.

If you are running locally it doesn't make sense that botdev.domain.com makes it work, since the traffic is not being redirected to ngrok.

Cheers,
Kamil

**Comment by alexisconia** [comment] 2019-03-14 17:09
Hello,
Yes it's running locally. I'm not sure to understand what do you mean by "the traffic is not being redirected to ngrok". I will receive the TCP connexion on my dev environment that's right?
Thanks

**Comment by ksikorsk** [comment] 2019-03-14 17:38
For local runs we use ngrok as a TCP tunnel.  The media flows from our service to ngrok, then tunnels to your local machine, then is forwarded to the `InstancePublicIPAddress`.  If you deploy the service somewhere that has a static ip, or if your dev box has a static ip, then you can route the traffic directly to that ip.

This is our configuration for local runs... can you send me some code snippets of your config?  I specifically care about your `remoteUri`, `ngrokUri` and `InstancePublicIPAddress`.

```cs
var builder = new CommunicationsClientBuilder(appName, appId, this.logger);
builder
    .SetAuthenticationProvider(authProvider)
    .SetNotificationUrl(remoteUri)
    .SetServiceBaseUrl(this.platformUri);
    
// Generate service fqdn: x.tcp.ngrok.io -> x.bot.domain.com
var ngrokTcpServer = ngrokUri.Split('.')[0];
var mediaServiceFqdn = $"{ngrokTcpServer}.bot.domain.com";

// Media platform
var mediaPlatform = new MediaPlatformSettings
{
    ApplicationId = key,
    MediaPlatformInstanceSettings = new MediaPlatformInstanceSettings
    {
        CertificateThumbprint = this.certificateThumbprint,
        InstanceInternalPort = this.MediaServiceDetails.LocalPort,
        InstancePublicPort = this.MediaServiceDetails.RemotePort,
        InstancePublicIPAddress = new IPAddress(0x0),
        ServiceFqdn = mediaServiceFqdn,
    },
};

builder.SetMediaPlatformSettings(mediaPlatform);
```

Also, does your local box have a public IP?  If so it is possible to use `botdev.domain.com` IF it points to your local box.

**Comment by rossbuggins** [comment] 2019-03-15 17:04
Hi, when you say forwarded to InstancePublicIPAddress, what should this address be? I’ve got a paid ngrok with custom domain and a wildcard cert for the custom domain terminating on ngrok. I’m just about to try pretty much the same as above, thanks

**Comment by ksikorsk** [comment] 2019-03-15 17:29
In the case of paid ngrok, the only difference is that you don't need to have your own DNS CNAME entry that points to x.tcp.ngrok.io (given that ngrok already provides you with that).  Everything else should be the same.

new IPAddress(0x0) => "0.0.0.0"

I'm not an expert in this, but a quick google search revealed "If it says 0.0.0.0 on the Local Address column, it means that port is listening on all 'network interfaces' (i.e. your computer, your modem(s) and your network card(s)).".

I think that is what allows the media platform to be discoverable from the ngrok process running locally.

**Comment by ksikorsk** [comment] 2019-03-15 18:14
Correction on the above... you'll still need a CName entry to the paid tcp uri.  The cert subject or SANs need to match the tcp uri.

**Comment by rossbuggins** [comment] 2019-03-15 19:38
So to confirm, that is configuring was ip the media sdk tcp port is opened up on? So if you wanted it on a specific ip (if you had more than one adapter) on the host that’s where you would set it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rossbuggins** [comment] 2019-03-15 19:41
And following on from that, I assume local port is what port is opened on the specified local adapter ip, but what’s the remote port for? Is that passed out (with the fqdn) on a response from the initial request in, telling teams where to send the audio to?

**Comment by ksikorsk** [comment] 2019-03-15 20:37
It is not recommended to have multiple media platforms running on the same instance.  If  you needed to do that the recommendation would be to decouple the media process from your other processes.

Regarding your question: "So if you wanted it on a specific ip (if you had more than one adapter) on the host that’s where you would set it?"

that is correct, if you know your local IP you could set it there.  Under what scenario would you have 2 different IPs in the same instance?

**Comment by rossbuggins** [comment] 2019-03-15 20:42
Just trying to fully understand the config options at the moment as I go through the samples.

Is the sdk open source?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ksikorsk** [comment] 2019-03-15 20:45
No problem, I'm trying to understand your scenario :)

It is not opensource today, but the plan is to open source it in the future.

**Comment by rossbuggins** [comment] 2019-03-15 20:47
Would be good to get it open, I‘d be keen to get involved.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ssulzer** [comment] 2019-03-15 21:22
@rossbuggins @ksikorsk @alexisconia 

FYI, setting InstancePublicIPAddress = 0.0.0.0 is just a work around to set it to null (i.e., you don't know what your local machine's publicly visible/NAT'd address is). Setting the InstancePublicIPAddress to 0.0.0.0 is not recommended for a production bot deployment running in Azure, but may be "good enough" for a bot running on a local dev machine.

ngrok is not involved at all with relaying the actual real-time audio/video media between the Skype/Teams caller and the bot running on your VM or local dev machine. 

The InstancePublicPort and InstanceInternalPort ports are to allow a TCP-based control channel to be established between the Skype/Teams calling system and the bot's media platform. For InstanceInternalPort, the bot application should select an otherwise unused local port value. For the InstancePublicPort, the requirement is that when the Skype/Teams calling system attempts to connect to 'ServiceFqdn:InstancePublicPort', it resolves to the IP address:InstanceInternalPort of the specific machine/VM running the bot.

The local machine certificate identified by CertificateThumbprint must contain a Subject Name or entry in the Subject Alternative Name (SAN) list which matches ServiceFqdn.

Thanks,
Stephen

**Comment by rossbuggins** [comment] 2019-03-15 21:50
Thanks for the detailed run through Stephen, appreciated.
________________________________

**Comment by rossbuggins** [comment] 2019-03-15 21:59
Question re load balancing and HA (once I run through the local media examples I assume will become more obvious) but do you run the signal and tcp endpoints on all nodes, with a calls signal and endpoint staying on the same node, or do you have a clusters of separate signal and tcp media end points?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rossbuggins** [comment] 2019-03-16 09:48
I've taken most of the code from the Hue Bot example and put it through into a .net console project using the WebHostBuilder - this is what I've been using up until now and all working ok.  For the hue bot, I came across a few bits, first being having the thumbprint in the wrong format (it needed all caps and no spaces) the last being that I needed to manually get the Microsoft.Sype.Bots.Media nuget package and then run MediaPlatformStartupScript.bat as admin.

I've got a video call coming in, which is being detected at the callback/calling api and the call incoming events are firing, with the callback/calling method responding with a 202 status of accepted.

The bot is handling the Clients OnIncomming, creating a local ILocalMediaSession  and answering the call with it.

The call Handler is getting the ILocalMediaSession and subscribing to the  VideoSocket.VideoMediaReceived event ok. However, I'm not getting any video media events and, I'm getting "Sorry, we couldn't connect you" in Teams.

Where do I start looking information of the actual connection has come in over TCP? Should I be looking anywhere in particular for this?

**Comment by rossbuggins** [comment] 2019-03-16 11:56
@ssulzer Just to confirm with ServiceFqdn, this should be set to the media tcp endpoint cname that is created, and this should to the certificate described by the certificate thumbprint? 

If this is set to 0.bot.contoso.com and 0.bot.contoso.com is cname to 0.tcp.ngrok.io (for example), this doesn't have the ngrok ssl termination cnames not matching issues, as the cert is being used to secure the incoming media tcp traffic with TLS, terminating at InstanceInternalPort (ie this is nothing to do with http ssl, its tls securing the raw incoming tcp media traffic). 

Does it need to be 0.bot.contoso.com - or could it just be a cname of botmedia.contoso.com =>0.tcp.ngrok.io?

**Comment by ssulzer** [comment] 2019-03-17 00:30
@rossbuggins 
Can you please share your bot application Id? I can take a look at our Skype/Teams calling side logs, to see if there is a problem validating the certificate associated with ServiceFqdn. If ServiceFqdn is "0.bot.contoso.com", then the certificate needs to include "0.bot.contoso.com" as a subject name or alternative name. As I mentioned, the certificate identified by CertificateThumpbrint needs to match the ServiceFqdn (as either the SN or an entry in the SAN list).

Resolving ServiceFqdn:InstancePublicPort should connect to the specific machine (at port InstanceInternalPort) hosting the bot (possibly via a reverse TCP proxy like ngrok). If your bot application is deployed across a cluster of machine/VM instances, resolving ServiceFqdn:InstancePublicPort should point to the specific machine instance within the cluster that is handling the particular bot call (i.e., the specific VM where you allocated the Audio/VideoSocket objects to handle the incoming call). For an Azure Cloud Service-based bot application, InstancePublicPort may be an InstanceInputEndpoint to identify a specific VM instance within the cluster.

Thanks,
Stephen

**Comment by rossbuggins** [comment] 2019-03-17 13:34
HI @ssulzer , the bot ID is 7f1b1765-588a-49e3-bbdb-9853ad46a2ae, thanks

**Comment by ssulzer** [comment] 2019-03-17 16:46
@rossbuggins 
Looks like a failure during the TLS handshake, but I am not certain of the underlying problem. I am not familiar with setting up ngrok. The error on our side:

**SecurityNegotiationException: Transport security negotiation failed due to an underlying IO error: Authentication failed because the remote party has closed the transport stream.. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.**

For establishing the secure TLS/TCP media control channel to the bot media platform, we require TLS 1.2 and support the following cipher suites:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH secp384r1
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH secp384r1
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp384r1
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   ECDH secp384r1

@ksikorsk 
Kamil, what is our guidance re: configuring TLS for an apphosted media bot running behind ngrok?

Thanks,
Stephen

**Comment by rossbuggins** [comment] 2019-03-17 16:57
Ok, I’ll do some digging into the tcp host this end and see what the cert is saying.

How can I enable the sdk to output trace/debug logging? I’m not getting much from it by default. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ssulzer** [comment] 2019-03-17 17:50
Bot SDK/media platform logging won't help, as the TLS handshake is handled lower in the OS / SSL subsystem. Please check in the Windows Event Viewer under "Windows Logs"\"System" for Schannel errors, to see if the TLS handshake made it (via the ngrok reverse proxy) to your machine running the bot app.
See the "Troubleshooting" section in this article about enabling verbose Secure Channel logging: https://kevinholman.com/2018/05/06/implementing-tls-1-2-enforcement-with-scom/

For reference, I was looking at a particular call failure to your bot which occurred on 2019-03-16 at around 10:02 UTC for CallId = 2f1a0900-45fa-4aa2-b83e-37021ec25604.

**Comment by rossbuggins** [comment] 2019-03-17 17:53
I did do some changes during yesterday, and the cert wasn’t matching the thumbprint for a while. Are you seeing that error at any point today?

________________________________

**Comment by ssulzer** [comment] 2019-03-17 18:18
For a call attempt today at 16:07 UTC for CallId = ead7188e-c56e-4464-9026-3d9ca8a559bd, I see the same error, "Authentication failed because the remote party has closed the transport stream."

**Comment by rossbuggins** [comment] 2019-03-17 19:37
In windows events I've got
_A fatal error occurred when attempting to access the TLS server credential private key. The error code returned from the cryptographic module is 0x8009030D. The internal error state is 10001._

Also get this:
_Exception calling "AuthenticateAsClient" with "1" argument(s): "Authentication failed because the remote party has closed the transport stream."_

from this powershell:
```
$tcpConnection = New-Object System.Net.Sockets.TcpClient("MYTCPCLIENTADDRESS", MYTCPCLIENTPORT)
$stream= $tcpConnection.GetStream()
$sslStream = New-Object System.Net.Security.SslStream $stream,$false
$sslStream.AuthenticateAsClient($computerName)

```

I'm using a wildcart cert of *.bot.[mydomain].com and the tcp media fqdn is set to 0.bot.[mydomain].com

I'm just grabbing a non wildcard cert to give that a go

**Comment by rossbuggins** [comment] 2019-03-17 20:05
Thanks @ssulzer for guidance on diagnosing, I can confirm that is was an issue with trying to use a wildcard cert, I got a non wildcard one and its working fine 👍

**Comment by ssulzer** [comment] 2019-03-17 20:36
@rossbuggins 

A wild card certificate should work. Based on the 0x8009030D error you saw, it seemed like the previous certificate was not installed properly (maybe the private key was not exported?).

https://blogs.msdn.microsoft.com/webapps/2017/04/28/a-fatal-error-occurred-when-attempting-to-access-the-ssl-server-credential-private-key-0x8009030d/

Glad to hear you got the bot call working. 👍

**Comment by rossbuggins** [comment] 2019-03-17 21:53
I saw that msdn blog, so I uninstalled the wildcard and reinstalled it, but it had the same issue.

**Comment by rossbuggins** [comment] 2019-03-17 21:55
@ksikorsk  re logging coming from the sdk in general (not TLS related per say) is there somewhere to tell it to be more verbose in what logs its outputting? Thanks

**Comment by ksikorsk** [comment] 2019-03-18 15:37
The samples have a controller to show you the last 1000 log entries:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/0d299364a72568af757c8bc9d2feb5d42cc67231/Samples/LocalMediaSamples/AudioVideoPlaybackBot/FrontEnd/Http/Controllers/DemoController.cs#L49-L60

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/0d299364a72568af757c8bc9d2feb5d42cc67231/Samples/LocalMediaSamples/AudioVideoPlaybackBot/FrontEnd/Http/Controllers/DemoController.cs#L71-L83

We restrict logs to only http traces, errors, and warnings:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/0d299364a72568af757c8bc9d2feb5d42cc67231/Samples/Common/Sample.Common/Logging/SampleObserver.cs#L99-L113

you can remove those if statements to give you all types of logs.  Although I'm not sure if that will have any meaning for you.  Errors/Warnings should already be displayed.

The other place to set log level is when initializing the GraphLogger:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/0d299364a72568af757c8bc9d2feb5d42cc67231/Samples/LocalMediaSamples/AudioVideoPlaybackBot/WorkerRole/WorkerRole.cs#L46

```cs
this.logger = new GraphLogger(typeof(WorkerRole).Assembly.GetName().Name, redirectToTrace: true);
this.logger.DiagnosticLevel = TraceLevel.Verbose;
```

Today the logs can only be observed on your end, we don't publish them anywhere like the media lib does.  That will come in the future.

**Comment by alexisconia** [comment] 2019-03-18 15:52
Thanks for these useful information. I'm running the bot on my local machine with a paid ngrok account and a SSL terminaison on my machine. If i understand correctly, that why i need this configuration on the servicefqdn attribute. Is it correct? Thanks

**Comment by ksikorsk** [comment] 2019-03-18 16:01
@ssulzer 
> Kamil, what is our guidance re: configuring TLS for an apphosted media bot running behind ngrok?

We don't have any... we haven't needed to do any configuration of TLS using free ngrok accounts (where SSL termination happens on ngrok.io).  We haven't tested with paid ngrok accounts (where SSL termination happens on the local machine).

**Comment by alexisconia** [comment] 2019-03-18 16:11
This is the configuration that i'm using on ngrok
```yaml
authtoken: XXXXXXXXXXXXXX
region: eu
tunnels:
    signalingtls:
        addr: 443
        proto: tls
        bind_tls: true
        hostname: bot.domain.com
    media:
        addr: 8000
        proto: tcp
        remote_addr: 1.tcp.eu.ngrok.io:22000
```
And my configuration is
```csharp
MediaPlatformInstanceSettings = new MediaPlatformInstanceSettings()
{
                    CertificateThumbprint = _botOptions.CertificateThumbprint,
                    InstanceInternalPort = serviceContext.CodePackageActivationContext.GetEndpoint("MediaPort").Port,
                    InstancePublicIPAddress = new IPAddress(0x0), 
                    InstancePublicPort = 22000,
                    ServiceFqdn ="bot.domain.com"
}
```

**Comment by rossbuggins** [comment] 2019-03-18 20:10
As the service fqdn is for the media tcp, isn’t the Tls is always done on client and not ngrok, as ngrok doesn’t touch tls on tcp forwards, both paid and free?

**Comment by rossbuggins** [comment] 2019-03-18 20:15
If you get a cert that exactly matches 1.bot.domain.com, and install that on your bot server and use the thumbprint for that, then does it work with 1.bot.domain.com as the fqdn?

**Comment by ksikorsk** [comment] 2019-03-18 21:23
From the ngrok site for paid accounts:

**End-to-End TLS Tunnels**
Tunnel HTTPS (or other TLS) traffic to your local services end-to-end encrypted with your own SSL certificate and private key. You can even run them over your own domains!
```
ngrok tls -hostname yourdomain.com 443
```

For this option to work, the your service (skype.bots.media) needs to accept the ssl handshake.

**TLS Client Termination**
Use ngrok's TLS tunnels with end-to-end encryption even if your local service doesn't support TLS termination by offloading it to the ngrok client!
```
ngrok tls -crt tls.crt -key tls.key 443
```

My understanding is that for free accounts ssl terminates at ngrok.io, and the traffic flowing between ngrok ---> ngrok client ---> service is unsecure.  It is possible that for unsecure connections it skips some validation that you may be seeing by using ngrok paid.

**Comment by rossbuggins** [comment] 2019-03-18 21:51
That’s for choosing tls which it does for securing http, but when you set a forward for tcp and reserve a host you can’t sent your own host name on ngrok or cert, so the tls for tcp has to be done by your own client ie media endpoint?

________________________________

**Comment by ksikorsk** [comment] 2019-07-04 18:10
Closing this issue as we don't provide official support for ngrok.

**Closed by ksikorsk** 2019-07-04 18:10 UTC
