### ISSUE TITLE
Call.AnswerAsync gives an error

### ISSUE THREAD

**Issue by jsweiler** [microsoftgraph/microsoft-graph-comms-samples#320] opened 2020-09-03 18:42 UTC
**Describe the issue**
Calling AnswerAsync on a call gives an error

**Graph SDK (please complete the following information):**
 - 1.2.0-beta.1702

**Call ID**
72202f00-851f-43e2-83bc-752f76268663 time:2020-09-03T18:34:06

**Additional context**
I see the following error when trying to answer an incoming call with the Graph sdk.
exception: Code: BadRequest
Message: The type 'microsoft.graph.answer' specified in the URI is neither a base type nor a sub-type of the previously-specified type 'microsoft.graph.call'.
Scenario Id: 310fc934-3989-48d4-8c83-ead923bc72ee
Inner error:
	AdditionalData:
	date: 2020-09-03T18:34:06
	request-id: a480a1c1-f5d2-4153-bd33-856eeff6d0c1

I just noticed this happening in the last hour.

**Comment by saraswat40** [comment] 2020-09-03 19:10
+1. We are also running into this issue.

**Comment by davides** [comment] 2020-09-03 19:10
+1. Started seeing the same error this morning as well.

**Comment by marcbertasius** [comment] 2020-09-03 20:26
Seeing the same with a customer. Have raised it with the developer, but it's looking like something changed in Graph...

**Comment by zihzhan** [comment] 2020-09-03 21:31
Hi, got confirmed root cause is Graph's bad schema rollout. 
They are rolling back the schemas version. I didn't get ETA from them but it should get fixed within one business day.
Sorry about the inconvenience.

**Comment by zihzhan** [comment] 2020-09-03 21:52
We got confirmed from the customers, everything is working fine again.

**Closed by zihzhan** 2020-09-03 21:52 UTC
