### ISSUE TITLE
Tracking a transferred call

### ISSUE THREAD

**Issue by rugt0r** [microsoftgraph/microsoft-graph-comms-samples#106] opened 2019-07-22 15:03 UTC
Hi
I'm trying to develop a bot which can answer a call and then transfer the caller through to someone else based on some internal criteria. I'm doing the transfer with a POST to the graph on app/calls/{id}/transfer.

Imagine we have two users, A and B:
- A calls bot
- Bot picks up and decides that B is required to take this call
- Bot calls B
- B picks up
- The bot transfers A to B

In this scenario, both the original calls (A-to-Bot and Bot-to-B) are terminated and we lose the ability to keep tracking the call. Is there any way to get further updates about the call after the transfer has occurred? We really need to know things like when the call ends and who is participating at a given time.

**Comment by mwerghemmi** [comment] 2019-07-24 07:31
Hi @rugt0r ,  

unfortunately the API don’t seem to permit this. 
once the call is transferred, from a Bot point of view, the track is completely lost. 
is it a kind of CC scenario that you are trying to achieve?

**Comment by rugt0r** [comment] 2019-07-24 08:25
Yeah, we want to track who the call is currently with and when it ends. 

If a bot transfers a call to a user, we lose track of it- we don't know when the user becomes available again, we don't know if they transferred the call further, we don't know when the call ends, etc.

**Comment by monkeyatcomputer** [comment] 2019-07-31 07:56
@rugt0r 

perhaps conference A and B participants and have the bot track conference progress?

further call transfers by A or B would have to be handled by the bot

**Comment by rugt0r** [comment] 2019-07-31 08:20
That's what I'm currently doing as a workaround. The problem is that then you don't get the native transfer functionality in Teams. So you either need to rely on people "transferring" the call by inviting another participant and then leaving themselves, or as you suggested, having the bot do the transfer. In the first scenario we don't seem to get any notification that the participants have been updated, so we don't know who left and who joined- this relates to one of the other issues I've raised regarding tracking participants.

All these attempts at workarounds are a bit clumsy. What we really need are reliable participant and call tracking. Without that it's hard to implement contact centre functionality.

**Comment by ksikorsk** [comment] 2019-09-10 22:20
@VinodRavichandran request to track transferred participants.

**Comment by VinodRavichandran** [comment] 2019-09-11 01:20
Same as the webhook enhancement requested here https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/99

FYI - @zhengni-msft

**Comment by rugt0r** [comment] 2019-09-13 13:43
We can see that a call has been ended by a transfer, but what we'd like is to be able to receive updates about that new call (and any onward transfers.)

Imagine a contact centre scenario where a customer calls in. Agent-A picks up, and transfers to Agent-B, who transfers to the call to their Supervisor. It would be useful to track this as if it was one call with multiple legs, having real-time information on who that customer is currently talking to, how long since their call was first answered, etc.

**Comment by ksikorsk** [comment] 2019-09-13 15:55
Today the only way to do this is to join the other call, and observe the participants.  Even then, the roster does not tell you the nature of how a participant joined/left the meeting.  I'm closing this bug as a duplicate of the one Vinod [linked](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/99).

**Closed by ksikorsk** 2019-09-13 15:55 UTC
Labels: enhancement

**Comment by rugt0r** [comment] 2019-09-16 09:04
@ksikorsk How do you mean "join the other call"? As far as I can tell, a bot cannot choose to join a call in progress... it can only answer a call, start a call, or dial into a pre-scheduled meeting.

**Comment by ksikorsk** [comment] 2019-09-16 16:28
If a bot has been granted `Calls.JoinGroupCall.All` or `Calls.JoinGroupCallAsGuest.All` permissions by the tenant admin, it can join existing meetings.  To do so the bot would require the meeting coordinates.  These can either be extracted from the join URL provided by the teams client, using the `OnlineMeetings` APIs, or provided to the bot when it is invited to the meeting.

All of our samples show the [join call scenario](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Controllers/JoinCallController.cs):
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/70295da8c9fc2ddf1b8538f0f7f49299ee268e3e/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Controllers/JoinCallController.cs#L55
